<?=  $this->translate('account_expiration_body', ['%%firstname%%' => $this->firstname, '%%expiration_date%%' => $this->expiration_date, '%%login_link%%' => $this->login_link]) ?> 

<?= $this->translate('account_expiration_name', ['%%name%%' => $this->firstname . ' ' . $this->lastname]) ?>
<?= $this->translate('account_expiration_email', ['%%email%%' => $this->email]) ?>

<?= $this->translate('account_expiration_account', ['%%username%%' =>  $this->username]) ?>
<?= $this->translate('account_expiration_login_method', ['%%login_method%%' => $this->login_method]) ?>
