<!-- START of: finna - search/streetsearch.phtml -->
<?
    $this->headTitle($this->translate('street_search'));
    $this->content()->setHeading = false;
    $this->layout()->finnaMainHeader = false;
    $this->body()->appendClass('streetsearch');

    $introText = '<div class="introduction"><h1 class="introductionText">' . $this->translate('street_search_header') . '</h1></div>';
    $terminateButton = '<button id="street-search-terminate">' . $this->transEsc('Abort') . '</button>';
    $infoText = '<div class="info"></div>';
    $infoArea = '<div>' . $infoText . $terminateButton . '</div>';
    $infoBox = '<div class="infoBox">' . $infoArea . '</div>';
    $spinnerContainer = '<div id="street-search-spinner" class="alert alert-info"><div class="fa fa-spinner fa-spin"></div>' . $infoBox . '</div>';
    $searchButton = '<button class="btn btn-primary" id="street-search-button">' . $this->transEsc('street_search_button') . '</button>';
    $searchButtonArea = '<div id="street-search-button-area">' . $searchButton . $spinnerContainer . '</div>';

    $this->layout()->searchbox = $introText . $searchButtonArea;
    
    $this->headScript()->appendFile('finna-street-search.js', 'text/javascript', '');
   
    $this->jsTranslations()->addStrings(
      array(
        'street_search_geolocation_inactive' => 'street_search_geolocation_inactive',
        'street_search_checking_for_geolocation' => 'street_search_checking_for_geolocation',
        'street_search_geolocation_available' => 'street_search_geolocation_available',
        'street_search_other_error' => 'street_search_other_error',
        'street_search_geolocation_inactive' => 'street_search_geolocation_inactive',
        'street_search_timeout' => 'street_search_timeout',
        'street_search_no_streetname_found' => 'street_search_no_streetname_found',
        'street_search_reversegeocode_unavailable' => 'street_search_reversegeocode_unavailable',
        'street_search_searching_for' => 'street_search_searching_for',
        'street_search_coordinates_found' => 'street_search_coordinates_found',
        'Abort' => 'Abort'
      )
    );
      
?>
<div class="row">
 <div class="col-md-10 col-lg-8">
   <ul id="street-search-output"></ul>
   <p>
     <?=$this->translate('street_search_info')?>
   </p>
 </div>
</div>
<!-- END of: finna - search/streetsearch.phtml -->
